name: Deploy API Reference 
on:
  push:
    paths:
      - '.resources/openapi/**'
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npx @redocly/cli build-docs --config=./.resources/openapi/openapi.yaml
          npx redoc-cli --output index.html bundle ./.resources/openapi/openapi.yaml
          git checout gh-pages
          git add index.html
          git commit -m "docs: gerado automaticamente index.html API reference"
          git push