name: Deploy API Reference 
on:
  push:
    paths:
      - '.resources/openapi/**'
  workflow_dispatch:
jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Generate Redoc Cli
        uses: actions/setup-node@v4
        with:
          node-version: 20.3.0
      - run: npx redoc-cli --output index.html bundle ./.resources/openapi/openapi.yaml
      - name: Publish Index ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          git checout gh-pages
          git add index.html
          git commit -m "docs: Index.html gerado automaticamente API reference"
          git push