name: Deploy API Reference 
on:
  push:
    paths:
      - '.resources/openapi/**'
      - '.github/workflows/deploy-gh-pages.yml'
  workflow_dispatch:
env:
  BRANCH_TARGET: gh-pages
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - run: |
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git fetch --all
          git checkout ${{ env.BRANCH_TARGET }} 
          git rebase ${{ github.ref }}
          git commit -m "'[Automated] Merged ${{ github.ref_name }} into target ${{ env.BRANCH_TARGET }}'"
          git push  
  generate-doc:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [merge-branch]
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Generate Redoc Cli
        uses: actions/setup-node@v4
        with:
          node-version: 20.3.0
      - run: npx redoc-cli --output index.html bundle ./.resources/openapi/openapi.yaml
      - name: Publish Index ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          git add index.html
          git commit -m "docs: Index.html gerado automaticamente API reference"
          git push